name : Build on PR

on : 
    pull_request:
        branches:
            - main

jobs :
    buildBackend :
        runs-on : ubuntu-latest
        steps :
            - name : checkout code
              uses : actions/checkout@v2
            - name : Install Dependencies
              run : |
                cd api
                npm install
            - name : Build backend
              run : |
                cd api
                node index.js &
                sleep 10
            - name : stop the backedn
              run : pkill -f "node index.js"
